### ISSUE TITLE
Help with Bootstrapping issue?

### ISSUE THREAD

**Issue by ghost** [UrbanInstitute/spark-social-science#4]
Hello Urban Institute (and Alex),

First, I would like to thank you for posting all of this valuable work to GitHub, and presenting on it this past summer at the AWS Summit.  Being able to access R and Jupyter this way will really be a boon to anyone that takes the time to implement it.

Unfortunately, I seem to have broken the implementation somehow.  The bootstrapping script is not completing.  It stalls while waiting for the file to appear in this chunk of the script: 
```
# install SparkR or the out-dated SparkR-pkg
if [ "$SPARKR" = true ] || [ "$SPARKR_PKG" = true ]; then 
  #the following are needed only if not login in as hadoop
  sudo mkdir /mnt/spark
  sudo chmod a+rwx /mnt/spark
  if [ -d /mnt1 ]; then
    sudo mkdir /mnt1/spark
    sudo chmod a+rwx /mnt1/spark
  fi
  
  if [ "$SPARKR" = true ]; then
    #wait file to show up
    while [ ! -d /usr/lib/spark/R/lib/SparkR ]
    do
      sleep 10
    done
    sleep 15
    sudo R --no-save << EOF
```
The AWS log:
```
* DONE (plyrmr)
Making 'packages.html' ... done
+ '[' true = true ']'
+ sudo mkdir /mnt/spark
+ sudo chmod a+rwx /mnt/spark
+ '[' -d /mnt1 ']'
+ '[' true = true ']'
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
+ '[' '!' -d /usr/lib/spark/R/lib/SparkR ']'
+ sleep 10
```

This occurs in both the master and slave nodes.  I haven't been able to deduce where the bootstrap expected the file to be created, and therefore I am having trouble fixing the issue myself.

Any advice or help would be greatly appreciated.  I have posted this here in case it is a larger issue.

Thanks,
John

**Comment by bricesh** [comment]
Hi John

Have you by any chance been able to resolve this issue? I'm experiencing it and I can't work out what to do.

It looks to me like the Spark installation is not (no longer?) happening when creating a cluster through CloudFormation. When I manually create a cluster with Spark as an application, the _/usr/lib/spark_ folder is  created as expected.

Thanks,
Brice

**Comment by ghost** [comment]
Ahhhhh, that's interesting Brice.  I have been able to get in contact with Urban separately via e-mail, but they weren't able to replicate the issue.  I'm still working on this but have other things eating my time right now.  I'll make sure to report back as I go.

**Comment by bricesh** [comment]
Thanks John.

An update from me: I've been able to get an environment up and running by using the _rstudio_sparkr_emr4-proc.sh_ script on a 'normally' created EMR cluster. It's a bit of a manual process (there are a few steps including opening ports 22 and 8787) but it's working...

**Comment by StevenMMortimer** [comment]
@jhotchx @bricesh I am running into the same issue. I SSH'ed into the master node and confirmed that the folder `/usr/lib/spark/R/lib/SparkR` exists, however that folder doesn't exist on slave nodes, so your bootstrap script just hangs waiting for that folder.

My solution was installing SparkR directly from GitHub instead of relying on the folder being included on each slave node. More specifically, I deleted these lines: 

```
  if [ "$SPARKR" = true ]; then
    #wait file to show up
    while [ ! -d /usr/lib/spark/R/lib/SparkR ]
    do
      sleep 10
    done
    sleep 15
  	sudo R --no-save << EOF
library(devtools)
install('/usr/lib/spark/R/lib/SparkR')
# here you can add your required packages which should be installed on ALL nodes
# install.packages(c(''), repos="http://cran.rstudio.com", INSTALL_opts=c('--byte-compile') )
EOF
  else
```

and replaced with

```
  if [ "$SPARKR" = true ]; then
  	sudo R --no-save << EOF
if (!require('devtools')) install.packages('devtools')
devtools::install_github('apache/spark@v2.0.2', subdir='R/pkg')
# here you can add your required packages which should be installed on ALL nodes
# install.packages(c(''), repos="http://cran.rstudio.com", INSTALL_opts=c('--byte-compile') )
EOF
  else
```
Just make sure to match the Spark version that you're launching your cluster with.

**Comment by ghost** [comment]
Using this method I have also found success - Thanks @ReportMort!

**Comment by alexcengler** [comment]
So, although I have been able to reproduce this (sometimes, which is odd), it wasn't preventing cluster launch for me. That said, I think the updates made recently should address this. Sorry for being terrible at responding to the issues here!
